#
#spring:
#  main:
#    banner-mode: off
#
#  datasource:
#    url: jdbc:h2:mem:test
##    url: jdbc:h2:mem:file ./test
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
#  #  url: jdbc:mysql://localhost:3306/BankApp
#  #    username: root
#  #    password: root
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
##spring:
##  jpa:
##    open-in-view: false
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.MySQL57Dialect
##
##  liquibase:
#server:
#  port: 8080
##    change-log: classpath:/db/changelog/changelog-master.xml
#
##настройки для postgresql
#
##spring.datasource.url=jdbc:postgresql://localhost/sweater
##spring.datasource.username=postgres
##spring.datasource.password=3123Mira
##spring.jpa.generate-ddl=true