spring:
  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  #  datasource:
  #    url: jdbc:h2:file:./db
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#  h2:
#    console:
#      enabled: true
#      path: /h2-console/